# Generated by Django 5.1.4 on 2024-12-31 20:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0002_event_bank_event_bkash_event_nagad_event_rocket'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='event',
            name='bank',
        ),
        migrations.RemoveField(
            model_name='event',
            name='bkash',
        ),
        migrations.RemoveField(
            model_name='event',
            name='nagad',
        ),
        migrations.RemoveField(
            model_name='event',
            name='rocket',
        ),
        migrations.AddField(
            model_name='event',
            name='bank_account_name',
            field=models.CharField(blank=True, help_text='Bank account name.', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='bank_account_number',
            field=models.CharField(blank=True, help_text='Bank account number.', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='bank_branch_name',
            field=models.CharField(blank=True, help_text='Bank branch name.', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='bank_city',
            field=models.CharField(blank=True, help_text='Bank city.', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='bank_country',
            field=models.CharField(blank=True, help_text='Bank country.', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='bank_name',
            field=models.CharField(blank=True, help_text='Bank name.', max_length=100),
        ),
        migrations.AddField(
            model_name='event',
            name='bank_routing_number',
            field=models.CharField(blank=True, help_text='Bank routing number.', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='bank_swift_code',
            field=models.CharField(blank=True, help_text='Bank SWIFT code.', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='bkash_account_number',
            field=models.CharField(blank=True, help_text='bKash account number.', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='bkash_payment_option',
            field=models.CharField(blank=True, choices=[('make payment', 'Make Payment'), ('send money', 'Send Money')], help_text='bKash payment option.', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='nagad_account_number',
            field=models.CharField(blank=True, help_text='Nagad account number.', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='nagad_payment_option',
            field=models.CharField(blank=True, choices=[('make payment', 'Make Payment'), ('send money', 'Send Money')], help_text='Nagad payment option.', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='rocket_account_number',
            field=models.CharField(blank=True, help_text='Rocket account number.', max_length=20),
        ),
        migrations.AddField(
            model_name='event',
            name='rocket_payment_option',
            field=models.CharField(blank=True, choices=[('make payment', 'Make Payment'), ('send money', 'Send Money')], help_text='Rocket payment option.', max_length=20),
        ),
    ]
