# Generated by Django 5.1.4 on 2025-01-01 08:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('events', '0003_remove_event_bank_remove_event_bkash_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='registration',
            name='payment_method',
            field=models.CharField(choices=[('bkash', 'bKash'), ('nagad', 'Nagad'), ('rocket', 'Rocket'), ('bank', 'Bank Transfer')], max_length=100),
        ),
        migrations.AlterField(
            model_name='registration',
            name='total_amount',
            field=models.PositiveIntegerField(default=0),
        ),
    ]
